name: 问题Bug提交
description: Create a bug report for Autospark.
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ 问题创建指引
        [existing issues]: https://github.com/iflytek/autospark/issues
  - type: checkboxes
    attributes:
      label: ⚠️ 请先阅读. ⚠️
      description: >
        搜搜历史问题](https://github.com/iflytek/autospark/issues)
        确保提交bug之前，已经查阅已有bug列表没有重复bug
      options:
        - label: 我已经搜过， 没有找到
          required: true

  - type: markdown
    attributes:
      value: |
        确保提交bug之前，已经查阅已有bug列表没有重复bug，且问题务必明确具体
        
        举例:
        ❌ - AutoSpark无法退出
        ✅ - 在执行 Write Tool后, Autospark一直在不停的写文件。
        
  - type: dropdown
    attributes:
      label: 你在哪个操作系统使用Autospark?
      description: >
        当前使用操作系统:
      options:
        - Windows
        - Linux
        - MacOS
        - Codespaces
        - Web Version
        - Other
        - 官方Docker 容器
    validations:
      required: true
      nested_fields:
        - type: text
          attributes:
            label: 指定一个操作系统
            description: 请指定你现在正在用的系统

  - type: dropdown
    attributes:
      label: 使用版本分支?
      description: |
        请选择出现问题的版本分支

      options:
        - Main
        - Dev (branch)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 你是使用星火大模型的账号实验的吗？
      description: >
        autospark基于SuperAGI， 如果有openai相关问题，不在本项目回复
      options:
        - 星火大模型
    validations:
      required: true

  - type: dropdown
    attributes:
      label: bug属于什么分类?
      description: >
        请选择bug分类
      options:
        - 安装使用
        - 资源管理器
        - 性能
        - 大模型实现
        - 星火效果
        - Prompt提示语
        - 工具插件
        - 智能代理【Agents】
        - 文档
        - 日志
        - 产品页面
        - Other
    validations:
      required: true
      autolabels: true
      nested_fields:
        - type: text
          attributes:
            label: 指定一个领域分类
            description: 请选择最合适的一个分类

  - type: textarea
    attributes:
      label: 描述你的问题
      description: 用尽可能清晰的语言描述你的问题 
    validations:
      required: true

  - type: textarea
    attributes:
     label: 如何复现?
     description: |
      大致复现步骤
    validations:
     required: false

  - type: markdown
    attributes:
      value: |
        ⚠️ Please keep in mind that the log files may contain personal information such as credentials. Make sure you hide them before copy/pasting it! ⚠️        
  - type: input
    attributes:
      label: 上传bug日志内容
      description: |
        上传错误日志内容，方便我们帮你定位，分析问题
    validations:
      required: True
