name: Bug report 
description: Create a bug report for Autospark.
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ 问题创建指引
        [existing issues]: https://github.com/iflytek/autospark/issues
  - type: checkboxes
    attributes:
      label: ⚠️ Check for existing issues before proceeding. ⚠️
      description: >
        请检索 [search the history](https://github.com/iflytek/autosparke/issues)
        确保提交bug之前，已经查阅已有bug列表没有重复bug
      options:
        - label: I have searched the existing issues, and there is no existing issue for my problem
          required: true

  - type: markdown
    attributes:
      value: |
        确保提交bug之前，已经查阅已有bug列表没有重复bug，且问题务必明确具体
        
        For example:
        ❌ - AutoSpark无法退出
        ✅ - After performing Write Tool, SuperAGI goes into a loop where it keeps trying to write the file.

  - type: dropdown
    attributes:
      label: Where are you using Autospark?
      description: >
        当前使用操作系统:
      options:
        - Windows
        - Linux
        - MacOS
        - Codespaces
        - Web Version
        - Other
    validations:
      required: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the system
            description: Please specify the system you are working on.

  - type: dropdown
    attributes:
      label: 使用版本分支?
      description: |
        请选择出现问题的版本分支

      options:
        - Main
        - Dev (branch)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 你是使用星火大模型的账号实验的吗？
      description: >
        autospark基于SuperAGI， 如果有openai相关问题，不在本项目回复
      options:
        - 星火大模型
    validations:
      required: true

  - type: dropdown
    attributes:
      label: bug属于什么分类?
      description: >
        请选择bug分类
      options:
        - Installation and setup
        - Resource Manager
        - Action Console
        - Performance
        - Marketplace
        - Prompt
        - Tools
        - Agents
        - Documentation
        - Logging
        - Other
    validations:
      required: true
      autolabels: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the area
            description: 请选择最合适的一个分类

  - type: textarea
    attributes:
      label: 描述你的问题
      description: 用尽可能清晰的语言描述你的问题 
    validations:
      required: true

  - type: textarea
    attributes:
     label: 如何复现?
     description: |
      Mention 代理名称, Agent Description and Agent Goals, along with Model selected. 
      Provide any other data which might be relevant for us to replicate this issue.
      ⚠️ Provide NO other data in this field  
    validations:
     required: false

  - type: markdown
    attributes:
      value: |
        ⚠️ Please keep in mind that the log files may contain personal information such as credentials. Make sure you hide them before copy/pasting it! ⚠️        
  - type: input
    attributes:
      label: Upload Error Log Content
      description: |
        Upload the error log content, this can help us understand the issue better. 
        To do this, you can simply copy the logs from the terminal with which you did 'docker compose up' or in a new terminal, 
        enter 'docker compose logs' and copy/paste the error contents to this field. 
        ⚠️ The activity log may contain personal data given to SuperAGI by you in prompt or input as well as 
        any personal information that SuperAGI collected out of files during last run. Please hide them before sharing. ⚠️
    validations:
      required: True
